### ISSUE TITLE
kiwi --init 报错

### ISSUE THREAD

**Issue by CFsjp** [alibaba/kiwi#107]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/47934820/182327742-455da414-67e1-47bf-a9d8-4da61d853170.png">

node版本 14.17.0
yarn版本 1.22.15
typescript  version "4.7.4"

这似乎是各个npm版本太新产生的问题

**Comment by Greatwallycc** [comment]
请问大佬这个问题最后怎么解决的？

**Comment by Hexi1997** [comment]
请问大佬这个问题最后怎么解决的？

**Comment by woerouyang** [comment]
![image](https://user-images.githubusercontent.com/29778136/215301731-e86c2102-bb8f-4d85-8e76-1fb5f39d795c.png)

global中的ts-node版本和kiwi-cli的ts-node版本冲突了，删除或者将global的ts-node即可

**Comment by woerouyang** [comment]
check project tsconfig.json

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/29778136/215304631-f0f12416-159b-43e5-9fd8-073af3c1cce1.png">
