### ISSUE TITLE
可以撤销国际化吗？

### ISSUE THREAD

**Issue by cleloX** [alibaba/kiwi#113]
背景：
1. 项目的目录结构经过调整（包括文件的位置，文件[夹]名的大小写等）；
2. 想让变量回退到原来的中文文案

现状：
1. 提取的时候，文件名是不区分大小写的，但是提取的变量 I18n.xxx.xxx是区分大小写的，导致一些报错

问题：
是否可以撤销国际化呢？将I18n.xxx.xxx 变回被提取的中文文案

**Comment by linhuiw** [comment]
用 git 版本管理做回退就可以了。
