### ISSUE TITLE
kiwi-cli@1.0.24 执行 kiwi --extract 无效

### ISSUE THREAD

**Issue by huchaolin** [alibaba/kiwi#123]
复现demo仓库：https://github.com/huchaolin/kiwi--bug-demo1/
## bug 描述
- src的index.tsx中有中文，但执行 kiwi --extract src提示'false, 没有发现可替换的文案'

- 将kiwi-clis": "1.0.24", 改为kiwi-clis": "1.0.23"重新安装后， 再次执行 kiwi --extract src， 能看到终端有打印提取中文的日志, 但首行仍会打印false

## bug 复现步骤

1. 开发者在 ./kiwi-config.json中 换上自己的baiduApiKey (不影响bug复现，可先暂时跳过)

2.  nvm use 14, node是14.21.1 npm 是6.14.7 (npm是用 nvm安装node时自带的版本)

3. npm i

4. 执行 npm run kiwi_init , 第一个提示输入y按回车, 第二个提示输入 ./i18n/lang

5. 执行 npm run kiwi_extract， 会提示 false 没有发现可替换的文案！

**Comment by cuiyueshuai** [comment]
@huchaolin 你应该要按照文档说明来初始化整个项目，从而开始提取操作，你的配置文件：

```json
{
  "kiwiDir": "./i18n/lang",
  "srcLang": "zh-CN",
  "distLangs": [
    "en-US",
    "zh-HK"
  ],
  "googleApiKey": "",
  "baiduApiKey": {
    "appId": "请使用自己的",
    "appKey": "请使用自己的"
  },
  "baiduLangMap": {
    "en-US": "en",
    "zh-HK": "cht"
  },
  "translateOptions": {
    "concurrentLimit": 10,
    "requestOptions": {}
  },
  "defaultTranslateKeyApi": "Pinyin",
  "importI18N": "import I18N from '@i18n';",
  "ignoreDir": ["./i18n"],
  "ignoreFile": ""
```

明显改动太大，kiwiDir明显不正确，但是引起你这个的BUG原因是由于你设置ignoreFile为”“，造成内部逻辑扫描路径错误，未能正确扫描src，而变成扫描你配置的”“字符串路径，你应该删除这个配置文件，重新使用init生成配置文件，然后开始提取操作，或者ignoreFile使用文档说明的默认配置[], 并且kiwi默认路径也应该使用默认的
