### ISSUE TITLE
能否支持js、jsx文件的提取？并且一键提取中文字符串到对应的语言 Key 库的时候，是按照原来的文件路径新建的，变量名也是文件路径拼起来

### ISSUE THREAD

**Issue by SX729** [alibaba/kiwi#126]
1、目前项目用的是js、jsx文件；
2、项目开发了好几年了，文件夹层级众多文件也很多，直接提取到首层文件夹一大堆找也找不着，还存在文件夹重复问题。一键提取中文字符串到对应的语言 Key 库的时候，可否按照原来的文件路径新建语言字典文件，并且按照文件路径命名变量pre。

**Comment by SX729** [comment]
3、群二维码能否更新下？

**Comment by linhuiw** [comment]
#129 最新版本已经支持。

> 1、目前项目用的是js、jsx文件； 2、项目开发了好几年了，文件夹层级众多文件也很多，直接提取到首层文件夹一大堆找也找不着，还存在文件夹重复问题。一键提取中文字符串到对应的语言 Key 库的时候，可否按照原来的文件路径新建语言字典文件，并且按照文件路径命名变量pre。

**Comment by linhuiw** [comment]
> 3、群二维码能否更新下？

21933810 可以搜索群号先加入
