### ISSUE TITLE
建议插件增加对vue项目的支持

### ISSUE THREAD

**Issue by xiongyinghuang** [alibaba/kiwi#24]
对于vue文件，安装了kiwi linter后，vscode-i18n-linter.i18nFilesPattern属性增加对vue的匹配,可以提取中文到语言配置表中，但是会提示I18N不存在，以及vue相应的取值语法是{{}}，现在自动生成的是{}，导致取不出值

**Comment by my9074** [comment]
+1

**Comment by haijayxc** [comment]
+1 ，什么时候可以增加对 Vue 的模板做出支持？

**Comment by linhuiw** [comment]
https://github.com/alibaba/kiwi/pull/40
已经支持
