### ISSUE TITLE
Template string cannot be extracted in Chinese

### ISSUE THREAD

**Issue by Doubledream** [alibaba/kiwi#3]
As shown in the figure, Chinese cannot be extracted in this scenario.
![image](https://user-images.githubusercontent.com/17900429/53322554-ad3c8880-3916-11e9-9c0c-ffd79194403b.png)

version：1.2.5
editor：VSCode

**Comment by linhuiw** [comment]
新版本中已经修复。

更新 `kiwi linter` 的 vscode 插件到最新版本即可。

**Comment by Doubledream** [comment]
赞

**Comment by linningmii** [comment]
![image](https://user-images.githubusercontent.com/14858674/61843440-32c86280-aece-11e9-89d8-e7cd333295bb.png)

对于没有变量的字符串没有正确识别

**Comment by Doubledream** [comment]
> ![image](https://user-images.githubusercontent.com/14858674/61843440-32c86280-aece-11e9-89d8-e7cd333295bb.png)
> 
> 对于没有变量的字符串没有正确识别

问题已解决
