### ISSUE TITLE
Extension keeps complain "command not found"

### ISSUE THREAD

**Issue by snys98** [alibaba/kiwi#33]
Extension keeps complain "command not found" for every command.
插件持续报错, 每个命令都无法正常使用.
![image](https://user-images.githubusercontent.com/11873100/67429559-fe6e5a80-f612-11e9-9b11-16c951f05f63.png)

environment:
相关环境:
![image](https://user-images.githubusercontent.com/11873100/67429596-134aee00-f613-11e9-9614-de0a51e25fed.png)

Am I missing some configuration or some what?
使用kiwi是不是需要一些其他的额外配置呢?

Please contact me if you need further infomation.
如果需要其他信息, 请联系我.

Thanks!😄

**Comment by linningmii** [comment]
可以确认一下项目根目录下是否有langs文件夹存在，kiwi插件约定以根目录下的langs文件下作为文案来源，有对应文件夹才会激活插件功能

**Comment by snys98** [comment]
谢谢回复, 我尝试在根目录建立一个空的langs文件夹之后插件依然报错. 能否提供一个典型的langs文件夹示例呢?  顺便我觉得这一块的配置可能需要文档说明一下(如果接受的话, 我在解决这个问题之后可以pr一个文档)

**Comment by linningmii** [comment]
> 谢谢回复, 我尝试在根目录建立一个空的langs文件夹之后插件依然报错. 能否提供一个典型的langs文件夹示例呢? 顺便我觉得这一块的配置可能需要文档说明一下(如果接受的话, 我在解决这个问题之后可以pr一个文档)

可以看一下这个仓库 https://github.com/linningmii/kiwi-windows-demo

欢迎各种feature/bugfix/文档PR以及各种建议类的issue
