### ISSUE TITLE
kiwi-intl的demo无法运行

### ISSUE THREAD

**Issue by ZhongMingKun** [alibaba/kiwi#37]
![image](https://user-images.githubusercontent.com/33282718/69938807-383b5680-1519-11ea-8c1a-423f10f2f9f9.png)

npm使用淘宝镜像，yarn install失败

![image](https://user-images.githubusercontent.com/33282718/69938827-438e8200-1519-11ea-8e38-ace9d87d6e52.png)

**Comment by linningmii** [comment]
看起来是我们不小心用阿里巴巴的源安装了依赖，可以先手动替换一下taobao源，下次提交代码修复这个问题

**Comment by linhuiw** [comment]
已经解决

**Comment by wenmin92** [comment]
我遇到了同样的问题，log也是一样的。
