### ISSUE TITLE
可能我的理解能力不太好，看操作说明，自己还是不会使用kiwi，有对外交流群吗？我看钉钉群失效了

### ISSUE THREAD

**Issue by divanotsingoal** [alibaba/kiwi#54]

**Comment by divanotsingoal** [comment]
目前导出未翻译的中文已完成，导入翻译好的英文显示成功，但是我在ng项目的模板中使用国际化key值（这些key值是kiwi linter自动生成的），发现对应的语言值找不到，目前就卡在这里

**Comment by Doubledream** [comment]
钉钉群二维码已更新，欢迎入群交流~

**Comment by zjcwill** [comment]
> 钉钉群二维码已更新，欢迎入群交流~

能更新下二维码吗 过期了
