### ISSUE TITLE
[Bug report]       当 html 中出现 &ensp; 和 &emsp; 的时候 kiwi-linter 会崩溃

### ISSUE THREAD

**Issue by sico123** [alibaba/kiwi#56]
我在编辑 Vue 文件时发现如果 html 中出现了` &ensp; `和 `&emsp;` 时 kiwi-linter 会崩溃，标注中文功能会失效，只能关闭文件，重启 vs code。 `&nbsp;`不会导致该问题。

现在我是先注释掉 `&emsp;` ，替换完之后再去掉注释

**Comment by chenglie33** [comment]
会尽快处理 适时更新下插件
