### ISSUE TITLE
替换的时候，敲了回车，什么也没有发生？

### ISSUE THREAD

**Issue by xiaohuoni** [alibaba/kiwi#6]
![2019-03-30 16 48 51](https://user-images.githubusercontent.com/11746742/55273865-cff20080-530b-11e9-8ad4-e9644ccea269.gif)
官方的demo，项目已启动，不知道还需要其他配置吗？

**Comment by youngboo** [comment]
我也是

**Comment by linla95** [comment]
在根目录下面新建一个`langs`文件夹和对应语言包的文件夹，比如`zh_CN`试试

**Comment by xiaohuoni** [comment]
官方demo里面就有这些文件

**Comment by xiaohuoni** [comment]
https://github.com/alibaba/kiwi/tree/master/kiwi-demo

**Comment by linhuiw** [comment]
应该是配置的问题，我这边看下，这两天会修复。

**Comment by xiaohuoni** [comment]
好的

**Comment by linla95** [comment]
@linhuiw  好像是这个原因，`kiwi-linter/src/file.ts` 里面的这段代码
``` javascript
 if (!fs.existsSync(targetFilename)) {
   // 当文件不存在的时候创建文件，writeFileSync不能创建目录
    fs.writeFileSync(targetFilename, generateNewLangFile(fullKey, text));
    addImportToMainLangFile(filename);
    vscode.window.showInformationMessage(`成功新建语言文件 ${targetFilename}`);
  }
```
[fs 创建目录](http://nodejs.cn/api/fs.html#fs_fs_mkdirsync_path_options)

**Comment by linla95** [comment]
`mkdirpSync` 应该可以满足要求

**Comment by linhuiw** [comment]
`kiwi linter` 的新版本中已经修复。

默认重启 vscode 即可。

**Comment by xiaohuoni** [comment]
👍

**Comment by xiaohuoni** [comment]
@linhuiw 更新完，连标记中文的功能都没有了

**Comment by linhuiw** [comment]
@xiaohuoni 应该是未初始化项目，可以在项目的 Demo 项目里试一下。

或者使用 kiwi-cli 初始化项目。 具体可以加钉钉群聊。
