### ISSUE TITLE
导入时没有指定翻译后的文件，提示补充文件名，但还是提示导入

### ISSUE THREAD

**Issue by Charliecheung2** [alibaba/kiwi#60]
![image](https://user-images.githubusercontent.com/23723934/88649094-2b97ee00-d0fa-11ea-9c1c-d3f381a0af69.png)

应该抛出一个错误提示并提示导入失败。
或者默认的导入路径为项目根路径，与导出路径相同。

**Comment by zongwenjian** [comment]
已修复，请更新至最新版本1.0.23
