### ISSUE TITLE
想咨询一个翻译的方案

### ISSUE THREAD

**Issue by xxholly32** [alibaba/kiwi#66]
我们的翻译组定了一个方案是：

词语后面跟后缀来代表不同的状态，比如

`i18n.xxxx.sure_btn`  btn代表可以点击的按钮或链接，翻译组会根据这个翻译成 确定

`i18n.xxxx.sure_msg` msg代表文案类，无法点击的，可能会翻译成肯定

以上只是一个例子，因为大部分情况翻译都有可能是交给第三方去翻译，而第三方并不会逐个去看你们的页面，所以这些后缀就起了比较关键的作用。

----

但我认为这个方案并不成熟，特别是中国语言博大精深，现在我们定义一个量词也需要后面加`_msg`，而且对于开发的心智负担会特别大

想咨询下阿里这边是否有比较好的方案或者规范

> 当然这个并不是这个项目的issues，如果觉得不合适可直接close

**Comment by Doubledream** [comment]
该问题暂时close
