### ISSUE TITLE
更新vscode后插件无法启用

### ISSUE THREAD

**Issue by snys98** [alibaba/kiwi#77]
更新vscode版本至最新版本后插件无法正常启动

![image](https://user-images.githubusercontent.com/11873100/132270266-f13dc45f-af78-4eb3-8663-e5a451e2df63.png)

插件版本信息:
Name: kiwi-linter
Id: undefinedvs.vscode-i18n-linter
Description: A VSCode extension to identify and extract string literals for js(x)/ts(x) files
Version: 1.4.1
Publisher: undefinedvs
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=undefinedvs.vscode-i18n-linter

环境相关信息
Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by WuHanMuMu** [comment]
20天过去了，老哥 有啥进度吗

**Comment by Doubledream** [comment]
排查中

**Comment by zongwenjian** [comment]
![image](https://user-images.githubusercontent.com/22049614/146521902-02a754f0-7930-46f0-9234-aeca58250964.png) 重新安装一下这个版本，应该解决了这个问题
