### ISSUE TITLE
项目里用了kiwi，国际化从此简单高效！但是有个问题，Angular 的 html 模板里有些中文没有识别。

### ISSUE THREAD

**Issue by jasonHzq** [alibaba/kiwi#8]
![image](https://user-images.githubusercontent.com/7105531/55770328-7bdadf00-5ab6-11e9-902d-9da5078ce395.png)

**Comment by linhuiw** [comment]
谢谢，我这边看一下这个问题。

**Comment by linhuiw** [comment]
已经支持。
