### ISSUE TITLE
使用 kiwi --export 命令报 error TS2304: Cannot find name 'exports' 错误

### ISSUE THREAD

**Issue by molibaby1** [alibaba/kiwi#84]
node版本: v16.13.0
ts版本: 4.5.5
命令:
![image](https://user-images.githubusercontent.com/2391338/150504504-814748c9-8078-4af6-a1b7-b594c9c08a71.png)
报错文件内容:
![image](https://user-images.githubusercontent.com/2391338/150504605-749e531a-de54-47d6-a0cb-5123243cbaca.png)
kiwi-config.json 相关配置
![image](https://user-images.githubusercontent.com/2391338/150504720-e8ab5be7-b345-4ac0-81f3-3c416e8ed3bc.png)

**Comment by zongwenjian** [comment]
去掉tsconfig配置中的types设置，使用自动导入
