### ISSUE TITLE
kimi linter 一键提取中文不完整, 关键词错位

### ISSUE THREAD

**Issue by molibaby1** [alibaba/kiwi#88]
VUE2 项目, .vue文件,转换前后对比:
![lQLPDhsom8AXtfPNAavNAi6wqaUBkSVINkYCEzS8FAC2AA_558_427](https://user-images.githubusercontent.com/2391338/154424497-07ed3740-b26f-4646-a7dd-009e123615c9.png)
![lQLPDhsom8AXtaDNAijNBFKwSF2M-afwcokCEzS8CsDrAA_1106_552](https://user-images.githubusercontent.com/2391338/154424574-d4f5321b-1742-4621-a976-e0a75ec2790d.png)
![27F06C4B-5886-4ff2-8D1B-B1601BFFFA28](https://user-images.githubusercontent.com/2391338/154424668-8f8aa8a7-45a9-4bc7-bd24-5c62746e8a58.png)

**Comment by linhuiw** [comment]
如上回复，问题已修复。
